name: Build

on:
  pull_request:
    branches:
    - "v2"
  push:
    branches:
    - "v2"
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number for manual deployment'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-deploy:
    name: ğŸš€ Build
    runs-on: ubuntu-latest
    needs: [lint-check]
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

  lint-check:

    name: ğŸ Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: actions/setup-python@v5

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install tools
        run: make install-tools

      - name: Run npm Lint
        run: |
          make install
          make npm-lint

      - name: Run Markdown Lint
        run: make markdown

      - name: Run Yaml Lint
        run: make yamllint

      - name: Run CodeSpell Lint
        run: make codespell
